name: Build and Package
on: [ push ]
jobs:
  build64:
    name: "Build 64-bit components"
    uses: "./.github/workflows/build.yml"
    with:
      name: build64
      output-prefix: XRFrameTools-build64-GHA${{github.run_number}}
      vcpkg-architecture: x64
  build32:
    name: "Build 32-bit components"
    uses: "./.github/workflows/build.yml"
    with:
      name: build32
      output-prefix: XRFrameTools-build32-GHA${{github.run_number}}
      cmake-architecture: Win32
      vcpkg-architecture: x86
      target: api-layers
      component: api-layers
  installer-generator:
    name: Build installer generator
    uses: "./.github/workflows/build-installer-generator.yml"
    with:
      output-prefix: XRFrameTools-GHA${{github.run_number}}