name: Build and Package
on: [ push ]
jobs:
  build64:
    name: "Build 64-bit components"
    uses: "./.github/workflows/build.yml"
    with:
      name: build64
      output-prefix: build64
      vcpkg-architecture: x64
  build32:
    name: "Build 32-bit components"
    uses: "./.github/workflows/build.yml"
    with:
      name: build32
      output-prefix: build32
      cmake-architecture: Win32
      vcpkg-architecture: x86
      target: api-layers
      component: api-layers
  installer-generator:
    name: Build installer generator
    uses: "./.github/workflows/build-installer-generator.yml"
  combine:
    name: Combine artifacts
    needs: [ build32, build64, installer-generator ]
    uses: "./.github/workflows/combine.yml"