name: Combine
on: [ workflow_call ]
jobs:
  combine:
    name: "Combine artifacts"
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: List artifacts
        run: Get-ChildItem -recurse
      - name: Make bundles
        id: bundle
        shell: pwsh
        run: |
          mkdir bundle
          mv build64 bundle/INSTALL_ROOT
          Move-Item build32/lib/* bundle/INSTALL_ROOT/lib/
          mv installer-generator/* bundle/
          
          Move-Item build64-debug-symbols debug-bundle
          Move-Item build32-debug-symbols/* debug-bundle/
          
          Add-Content $env:GITHUB_OUTPUT "version=$(Get-Content bundle/INSTALL_ROOT/installer/version.txt)"
      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: XRFrameTools-v${{steps.bundle.outputs.version}}-bundle
          path: bundle
      - name: Upload debug bundle
        uses: actions/upload-artifact@v4
        with:
          name: XRFrameTools-v${{steps.bundle.outputs.version}}-DebugSymbols
          path: debug-bundle
      - name: install WiX
        run: |
          # Don't actually care about these specific versions, but as of 2025-03-11, just
          # saying 'wix' will pull in a broken mix of WiX5 and the WiX6 beta
          dotnet tool install --global wix --version 5.0.2
          wix extension add -g WixToolset.UI.wixext/5.0.2
      - name: Build installer
        shell: pwsh
        id: build-installer
        working-directory: bundle
        run: |
          ./XRFrameTools-Installer.exe `
            "$(Get-Location)/INSTALL_ROOT" `
            --stamp-file ${{github.workspace}}/installer.stamp
          $InstallerPath = Get-Content ${{github.workspace}}/installer.stamp
          $InstallerName = (Get-Item $InstallerPath).Name
          Add-Content $env:GITHUB_OUTPUT "installer-path=${InstallerPath}"
          Add-Content $env:GITHUB_OUTPUT "installer-name=${InstallerName}"
      - name: Upload unsigned installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.build-installer.outputs.installer-name}}
          path: ${{steps.build-installer.outputs.installer-path}}
